### PR TITLE
Add suggested changes to FileUpload section

### PR DESCRIPTION
**Pull request by vijayvenkatj**
continuation of https://github.com/CSYClubIIITK/CTF-Guide/pull/6

### CODE REVIEW

**Comment by errorxyz** [comment]
Have all the changes been made?

**Comment by vijayvenkatj** [comment]
> Have all the changes been made?

Yes

**Comment by errorxyz** [comment]
[this](https://github.com/CSYClubIIITK/CTF-Guide/pull/6#discussion_r1643911497), [this](https://github.com/CSYClubIIITK/CTF-Guide/pull/6#discussion_r1643901060) and [this](https://github.com/CSYClubIIITK/CTF-Guide/pull/6#discussion_r1643897710) are yet to addressed. The second and third one are nice-to-haves(optional) but the first one should be resolved.

**Comment by errorxyz** [comment]
@vijayvenkatj I've removed the insufficient blacklisting section for now as the content isn't very clear, especially the solution section. we can add an improved version later

**Pull request merged**
